<?php

use Drupal\Core\Controller\ControllerBase;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\commerce\commerce_product;
use Drupal\commerce;
use Drupal\commerce_price\Price;
use Drupal\commerce_cart;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\commerce_cart\CartProviderInterface;
use Drupal\commerce_cart\CartManagerInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\commerce_product\Entity\Product;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Drupal\commerce_order\Entity\OrderInterface;
use Drupal\commerce_order\Entity\LineItem;

function commerce_date_filter_theme($existing, $type, $theme, $path)
{
    return [
        'product_display' => [
            'variables' => [
                'products' => [],
                'form'    => [],

            ],
            'needs_environment' => true,
        ],
    ];
}

function commerce_date_filter_user_login($account)
{
    $uid = $account->get('uid')->value;
    $query = \Drupal::entityQuery('commerce_order')
        ->condition('uid', $uid)
        ->condition('state', 'draft')
        ->accessCheck(TRUE);
    $orderIds = $query->execute();

    // dd($orderIds);
    $lastOrderId = end($orderIds);
    $orders = \Drupal\commerce_order\Entity\Order::loadMultiple($orderIds);
    foreach ($orders as $key => $order) {
        // dd($order);
        if ($order->id() != $lastOrderId) {
            foreach ($order->getItems() as $item) {
                $item->delete();
            }
            $order->save();
        }
    }
}
